name: Bonniewalters
favicon: null
layout_spectrum: 0
typography_spectrum: 0.40967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.25
  lightness: 0.19482847792096436
  saturation: 0.09062496642582119
  rhythmicContrast: 0.9891908862628043
purpose: []
