name: Bonniewalters
favicon: null
layout_spectrum: 0.75963
typography_spectrum: 0.40967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f2f7'
    - '#000000'
    - '#252122'
    - '#43525e'
    - '#90adc6'
  brandStrength: 0.9375
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.9891908862628043
purpose: []
